### ISSUE TITLE
Alt tag is not dynamic inside the home page articles

### ISSUE THREAD

**Issue by garethjax** [aegis4048/pelican-aegis-jupyter-theme#3]
Hello,
i've just noticed that the articles displayed on the home page have a static alt value that it's : 

- "Neural Transfer Learning for Natural Language Processing (PhD thesis)".

**Comment by aegis4048** [comment]
Thanks for letting me know. I plan to change the design of the pages pretty soon and update that part too. The current version of this theme will be replaced with a new version, and I will create a separate repo for the current one.
